Repository open-cluster-management-io/multicloud-integrations, pull requests merged in 2023-03, with the labels that each got.

#34 update propagation code with status sync
  .github/workflows/go-presubmit.yml
  Makefile
  cmd/propagation/main.go
  deploy/controller/deploy.yaml
  deploy/controller/operator.yaml
  deploy/ocm/install.sh
  e2e/hub/clusterset-binding.yaml
  e2e/hub/guestbook-app-placement.yaml
  e2e/hub/guestbook-app-set.yaml
  e2e/hub/ocm-placement-consumer-role.yaml
  e2e/hub/ocm-placement-consumer-rolebinding.yaml
  e2e/hub/ocm-placement-generator-cm.yaml
  e2e/hub/project.yaml
  e2e/managed/apply-managed-clusterrole.yaml
  e2e/managed/apply-managed-clusterrolebinding.yaml
  e2e/managed/project.yaml
  e2e/run_e2e.sh
  examples/argocd/gitopscluster.yaml
  hack/test/e2e/argo-cd-install.yaml
  hack/test/openshift-gitops_appset-1.yaml
  pkg/apis/argocd/v1alpha1/types.go
  pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller_test.go
  propagation-controller/application/application_controller.go
  propagation-controller/application/application_status_controller.go
  propagation-controller/application/helper.go
  propagation-controller/application/helper_test.go
Labels: approved, lgtm

#35 enhance e2e with more validations
  e2e/hub/guestbook-app-set.yaml
  e2e/hub/project.yaml
  e2e/managed/project.yaml
  e2e/run_e2e.sh
Labels: approved, lgtm

#36 do not start the propgation controller until the argo cd application CRD is installed
  .github/workflows/go-presubmit.yml
  cmd/propagation/main.go
  deploy/controller/operator.yaml
  e2e/run_e2e.sh
Labels: do-not-merge/hold, approved, lgtm

#37 search empty apiversion related items causes resource sync controlle…
  Makefile
  pkg/controller/gitopssyncresc/gitopssyncresc_controller.go
Labels: approved

#38 resource sync controller crashed due to empty search items
  pkg/controller/gitopssyncresc/gitopssyncresc_controller.go
  pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller_test.go
Labels: approved

#41 Skip local-cluster propagation
  propagation-controller/application/application_controller.go
  propagation-controller/application/application_controller_test.go
Labels: approved, lgtm

#42 update some label and anno domain name to be ocm-io
  e2e/hub/guestbook-app-set.yaml
  propagation-controller/application/application_controller.go
Labels: approved, lgtm

#43 conform propgation cmd to the other cmd args
  cmd/propagation/main.go
  deploy/controller/operator.yaml
Labels: approved, lgtm

#44 Add ArgoCD Integration - Pull Model Architecture diagram
  docs/argocd-pull-model-architecture.png
Labels: approved, lgtm

#45 Enhance Application status message
  e2e/run_e2e.sh
  propagation-controller/application/application_status_controller.go
Labels: approved, lgtm

#46 Update go to 1.20
  .github/workflows/go-postsubmit.yml
  .github/workflows/go-presubmit.yml
  .github/workflows/go-release.yml
  build/Dockerfile
  build/Dockerfile.prow
  build/run-code-lint.sh
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  go.mod
  go.sum
  pkg/controller/gitopssyncresc/gitopssyncresc_controller.go
  pkg/utils/placement.go
Labels: approved, lgtm

#48 ACM-4395 Truncate hosting appset label to align with character limit
  pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller.go
  pkg/controller/multiclusterstatusaggregation/multiclusterStatusAggregation_controller_test.go
Labels: approved, lgtm

#47 ACM-4382: Security vulnerabilities
  pkg/controller/gitopscluster/gitopscluster_controller.go
  pkg/controller/gitopssyncresc/gitopssyncresc_controller.go
Labels: do-not-merge/hold, approved, lgtm

#49 rename enablePullModel to createBlankClusterSecrets to better capture other usecases outside of pull model
  deploy/crds/apps.open-cluster-management.io_gitopsclusters.yaml
  examples/argocd/gitopscluster.yaml
  examples/openshift-gitops/gitopscluster.yaml
  pkg/apis/apps/v1beta1/gitopscluster_types.go
  pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
  pkg/controller/gitopscluster/gitopscluster_controller.go
Labels: approved, lgtm
